kotlin.code.style=official
org.gradle.jvmargs=-Xmx4000m

base_group=dev.trashcode07.trashaddons
mod_id=trashaddons
mod_name=TrashAddons
mod_version=1.0.4

# https://fabricmc.net/develop/
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Dependency Versions
fabric_api_version=0.153.0+26.2
